apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: velero
  namespace: velero-system
spec:
  interval: 1m
  chart:
    spec:
      chart: velero
      version: '10.0.1'
      sourceRef:
        kind: HelmRepository
        name: velero
        namespace: velero-system
      reconcileStrategy: Revision
      interval: 1m
  targetNamespace: velero-system
  valuesFrom:
  - kind: ConfigMap
    name: velero-values
    valuesKey: values.yaml
