apiVersion: config.porch.kpt.dev/v1alpha1
kind: PackageVariant
metadata:
  name: example-argocd
spec:
  annotations:
    approval.nephio.org/policy: initial
  upstream:
    package: argo-cd
    repo: catalog-nephio-core
    revision: v2.0.0
  downstream:
    package: example-argocd
    repo: mgmt-staging
  injectors:
  - kind: WorkloadCluster
    name: example
