apiVersion: config.porch.kpt.dev/v1alpha1
kind: PackageVariant
metadata:
  name: example-argoapp-akri
spec:
  # annotations:
  #   approval.nephio.org/policy: initial
  upstream:
    package: argoapp-akri
    repo: catalog-nephio-optional
    revision: v2.0.0
  downstream:
    package: example-argoapp-akri
    repo: mgmt-staging
  injectors:
  - kind: WorkloadCluster
    name: example
  pipeline:
    mutators:
    - image: gcr.io/kpt-fn/set-annotations:v0.1.4
      configMap:
        nephio.org/cluster-name: example
