apiVersion: workload.nephio.org/v1alpha1
kind: NFDeployment
metadata: 
  name: du-example
  namespace: example
spec:
  provider: du.openairinterface.org
  interfaces:
  - name: f1
    ipv4:
      address: 192.168.10.8/24
      gateway: 192.168.10.1
  parametersRefs:
  - apiVersion: workload.nephio.org/v1alpha1
    kind: NFConfig
    name: du-nf-config
  - apiVersion: ref.nephio.org/v1alpha1
    kind: Config
    name: oai-cucp-config