apiVersion: workload.nephio.org/v1alpha1
kind: NFDeployment
metadata: 
  name: du-example
  namespace: example
spec:
  provider: du.openairinterface.org
  interfaces:
  - name: f1
    ipv4:
      address: 172.18.0.28/24
      gateway: 172.18.0.1
  parametersRefs:
  - apiVersion: workload.nephio.org/v1alpha1
    kind: NFConfig
    name: du-nf-config
  - apiVersion: ref.nephio.org/v1alpha1
    kind: Config
    name: oai-cucp-config