apiVersion: source.toolkit.fluxcd.io/v2beta1
kind: HelmRepository
metadata:
  name: velero
  namespace: velero-system
spec:
  # type: oci
  interval: 1m
  url: https://vmware-tanzu.github.io/helm-charts
