apiVersion: fn.kpt.dev/v1alpha1
kind: StarlarkRun
metadata: # kpt-merge: /generate-values
  name: generate-values
  annotations:
    config.kubernetes.io/local-config: "true"
    internal.kpt.dev/upstream-identifier: fn.kpt.dev|StarlarkRun|default|generate-values
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
source: |-
  load("krmfn.star", "krmfn")
  def set_values(resources):
    clusterName = ""

    # if a WorkloadCluster exists, and was injected, then use that for the name

    for r in resources:
      if krmfn.match_gvk(r, "infra.nephio.org/v1alpha1", "WorkloadCluster") and "annotations" in r["metadata"] and "kpt.dev/injected-resource" in r["metadata"]["annotations"]:
        clusterName = r["spec"]["clusterName"]
      
    for r in resources:
      if krmfn.match_gvk(r, "apps/v1", "Deployment"):
        r["metadata"]["name"] = clusterName+"-nginx"
        r["metadata"]["annotations"]["transition.dcnlab.ssu.ac.kr/v1"] = "clusterName="+clusterName
      if krmfn.match_gvk(r, "v1", "Service"):
        r["metadata"]["name"] = clusterName+"-nginx"

  set_values(ctx.resource_list["items"])
