apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: OpenStackMachineTemplate
metadata:
  name: example-control-plane
  namespace: default
spec:
  template:
    spec:
      flavor: m1.large
      image:
        filter:
          name: kube-ubuntu2004
      sshKeyName: mykey
