apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minio
  namespace: minio-system
spec:
  interval: 1m
  chart:
    spec:
      chart: minio
      version: '17.0.1'
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: minio-system
      reconcileStrategy: Revision
      interval: 1m
  targetNamespace: minio-system
  valuesFrom:
  - kind: ConfigMap
    name: minio-values
    valuesKey: values.yaml
