apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
kind: AWSMachineTemplate
metadata:
  name: aws-nephio-md-0
  namespace: default
spec:
  template:
    spec:
      ami:
        id: ami-0a1cfa462ff5dc5d9
      iamInstanceProfile: nodes.cluster-api-provider-aws.sigs.k8s.io
      instanceType: c5.4xlarge
      sshKeyName: mynephio2025
      rootVolume:
        size: 200
